In [17]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import *

if __name__ == '__main__':
    spark = SparkSession.builder.appName("Analise Coches ").getOrCreate()

    esquema = StructType([
        StructField("Marca", StringType(), True),
        StructField("Modelo", StringType(), True),
        StructField("Precio", IntegerType(), True),
        StructField("KM", FloatType(), True),
        StructField("Año", IntegerType(), True),
        StructField("Tipo_de_combustible", StringType(), True),
        StructField("CV", FloatType(), True),
        StructField("Ubicacion", StringType(), True),
        StructField("Transmision", StringType(), True),
        StructField("Codigo_postal", StringType(), True),
        StructField("Comunidad_autonoma", StringType(), True),
    ])

    df = spark.read.csv("coches.csv", header=True, schema=esquema)

    df.createOrReplaceTempView("coches")
    
    print("Coches por comunidad autonoma")
    df.groupBy("Comunidad_autonoma").count().orderBy(desc("count")).show()
    
    print("Coches por transmision")
    df.groupBy("Transmision").count().show()
    
    print("Coche con más kilometraje")
    df.select("Marca","Modelo", "KM").orderBy(desc("KM")).show(1)

    print("Precio medio por marca")
    df.filter("Marca IS NOT NULL") \
      .groupBy("Marca") \
      .agg(round(avg("Precio"), 2).alias("precio_medio")) \
      .orderBy(desc("precio_medio")) \
      .show()

<class 'pyspark.sql.dataframe.DataFrame'>
Coches por comunidad autonoma
+--------------------+-----+
|  Comunidad_autonoma|count|
+--------------------+-----+
|              Madrid| 5446|
|           Andalucía| 3549|
|            Cataluña| 3349|
|Comunidad Valenciana| 2676|
|             Galicia| 1034|
|          País Vasco| 1001|
|    Región de Murcia|  915|
|  Castilla-La Mancha|  618|
|              Aragón|  492|
|     Castilla y León|  480|
|            Asturias|  429|
|             Navarra|  348|
|            Canarias|  320|
|         Extremadura|  285|
|           Cantabria|  230|
|            Baleares|  204|
|            La Rioja|  175|
|         Desconocida|   29|
|               Ceuta|    3|
|             Melilla|    1|
+--------------------+-----+

Coches por transmision
+--------------+-----+
|   Transmision|count|
+--------------+-----+
|    Automático|13068|
|          null|  150|
|        Manual| 8339|
|Semiautomático|   27|
+--------------+-----+

Coche con más kilometraje
+-------------+------+---------+
|        Marca|Modelo|       KM|
+-------------+------+---------+
|Mercedes-benz|sl 280|9999999.0|
+-------------+------+---------+
only showing top 1 row

Precio medio por marca
+------------+------------+
|       Marca|precio_medio|
+------------+------------+
|      Pagani|   5800000.0|
|     Ferrari|   461820.03|
| Rolls-royce|   455771.26|
|     Mclaren|   400837.48|
| Lamborghini|   394570.92|
|     Maybach|   307933.33|
|Aston martin|   256495.19|
|     Bentley|   216352.65|
|    Wiesmann|    189850.0|
|         Ram|   116642.38|
|      Alpina|    115380.0|
|       Lotus|   105701.24|
|          Ac|    103680.0|
|   De tomaso|    103300.0|
|         Gmc|   100549.47|
|    Cadillac|    94345.08|
|       Ineos|    89944.63|
|       Voyah|     86870.0|
|         Ktm|    86366.67|
|      Morgan|    84406.47|
+------------+------------+
only showing top 20 rows